import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

// Metadatos del sitio
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}
