import React from "react";

import "./globals.css";



// Metadatos del sitio
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* Enlace al archivo CSS de Bootstrap */}
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossOrigin="anonymous"
      ></link>
      {/* Cuerpo de la página */}
      <body>{children}</body>
      {/* Script de Bootstrap */}
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous"
      ></script>
    </html>
  );
}

